using UnityEngine;

namespace FK.ConstantsGenerator
{
    /// <summary>
    /// Config Data for Constants Generator
    /// </summary>
    public class ConstantsGeneratorConfig : ScriptableObject
    {
        public string Namespace = "C";
        public string GeneratedClassesPath = "Scripts/_autoGenerated";
    }
}